from odoo import models, fields, api
from dateutil.relativedelta import relativedelta

class TransitDriverCron(models.Model):
    _inherit = 'transit.driver'

    @api.model
    def _cron_check_driver_license_expiry(self):
        """Find drivers with license expiring in 30 days or already expired,
        and create activities/chatter warnings for the Safety Officers.
        """
        today = fields.Date.today()
        warning_date = today + relativedelta(days=30)
        
        # Find drivers who are not already suspended/expired, but license is expiring soon
        expiring_drivers = self.search([
            ('license_expiry', '<=', warning_date),
            ('license_status', 'in', ['expiring', 'expired']),
        ])
        
        if not expiring_drivers:
            return
            
        safety_group = self.env.ref('transit_ops.group_safety_officer', raise_if_not_found=False)
        safety_users = safety_group.users if safety_group else self.env['res.users']
        activity_type = self.env.ref('mail.mail_activity_data_todo', raise_if_not_found=False)
        
        for driver in expiring_drivers:
            # Post chatter message
            driver.message_post(
                body=f"<b>License Alert:</b> Driver license ({driver.license_number}) "
                     f"expires on {driver.license_expiry}. License status is '{driver.license_status.upper()}'.",
                message_type='comment'
            )
            
            # Create Odoo activity for Safety Officers
            if safety_users and activity_type:
                for user in safety_users:
                    # Check if activity already exists to prevent duplicates
                    existing = self.env['mail.activity'].search([
                        ('res_model', '=', 'transit.driver'),
                        ('res_id', '=', driver.id),
                        ('user_id', '=', user.id),
                        ('summary', '=', 'Driver License Expiry Warning')
                    ])
                    if not existing:
                        self.env['mail.activity'].create({
                            'activity_type_id': activity_type.id,
                            'note': f"Driver {driver.name}'s license is expiring on {driver.license_expiry}. Please review.",
                            'summary': 'Driver License Expiry Warning',
                            'res_id': driver.id,
                            'res_model_id': self.env['ir.model']._get('transit.driver').id,
                            'user_id': user.id,
                            'date_deadline': driver.license_expiry,
                        })


class TransitVehicleCron(models.Model):
    _inherit = 'transit.vehicle'

    @api.model
    def _cron_check_vehicle_odometer(self):
        """Checks if a vehicle has accumulated 10,000+ km since last maintenance (or total).
        If so, creates an active maintenance log (which automatically sets status to In Shop).
        """
        active_vehicles = self.search([('status', '!=', 'retired')])
        
        for vehicle in active_vehicles:
            # Find last maintenance date
            last_maint = self.env['transit.maintenance'].search([
                ('vehicle_id', '=', vehicle.id),
                ('state', '=', 'closed')
            ], order='date desc', limit=1)
            
            run_distance = 0.0
            if last_maint:
                # Sum distance of trips after last maintenance date
                trips = self.env['transit.trip'].search([
                    ('vehicle_id', '=', vehicle.id),
                    ('state', '=', 'completed'),
                    ('date_start', '>', last_maint.date)
                ])
                run_distance = sum(trips.mapped('actual_distance'))
            else:
                # No maintenance done yet, check total odometer
                run_distance = vehicle.odometer or 0.0
                
            if run_distance >= 10000.0:
                # Post to vehicle chatter
                vehicle.message_post(
                    body=f"<b>Maintenance Alert:</b> Vehicle has run {run_distance:.1f} km "
                         f"since last maintenance (limit: 10,000 km). Creating auto maintenance ticket.",
                    message_type='comment'
                )
                
                # Auto-create active maintenance (will move vehicle status to In Shop via transit.maintenance.create)
                self.env['transit.maintenance'].create({
                    'vehicle_id': vehicle.id,
                    'service_type': 'Scheduled Odometer Maintenance (Auto)',
                    'notes': f"Auto-generated by scheduler. Accumulated mileage: {run_distance:.1f} km.",
                    'state': 'active',
                    'date': fields.Date.today()
                })
